### ISSUE TITLE
PHP 7.4 Error: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead 

### ISSUE THREAD

**Issue by michidk** [janmenzel/AuthOpenIDConnect#15]
Error in `/var/www/html/upload/plugins/AuthOpenIDConnect/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(973)`:

array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead

Updating the `jumbojett/openid-connect-php` dependency will fix it: https://github.com/jumbojett/OpenID-Connect-PHP/pull/191/files

**Comment by janmenzel** [comment]
Hello @michidk, thanks for this hint.

I will look at this problem and your other suggestion very soon.

**Comment by Breee** [comment]
So, i checked out your repo and changed the Version of the dependency to the latest Version. Then i have built the plugin and zipped it.

And it works as expected with limesurvey

**Comment by michidk** [comment]
> 
> 
> composer.json:
> 
> ```json
> {
>     "name": "janmenzel/auth-openid-connect",
>     "description": "OpenID Connect Authentication Plugin for LimeSurvey.",
>     "require": {
>         "jumbojett/openid-connect-php": "^0.9.2"
>     }
> }
> ```
> 
> So, i checked out your repo and changed the Version of the dependency to the latest Version. Then i have built the plugin and zipped it.
> 
> And it works as expected with limesurvey

Which PHP version are you using?

**Comment by Breee** [comment]
> > composer.json:
> > ```json
> > {
> >     "name": "janmenzel/auth-openid-connect",
> >     "description": "OpenID Connect Authentication Plugin for LimeSurvey.",
> >     "require": {
> >         "jumbojett/openid-connect-php": "^0.9.2"
> >     }
> > }
> > ```
> > 
> > 
> > So, i checked out your repo and changed the Version of the dependency to the latest Version. Then i have built the plugin and zipped it.
> > And it works as expected with limesurvey
> 
> Which PHP version are you using?

uhm, 7.4. 
but I just used the composer:latest docker image to build it. 
And from the logs [here](https://hub.docker.com/layers/composer/library/composer/latest/images/sha256-889a212995c122c0b49efaf4ab82895ff7af8bd695fac69f05addb1b13b9e18b?context=explore)

it seems to be 7.4.14

```
docker run --rm --interactive --tty   --volume $PWD:/app   --user $(id -u):$(id -g)   composer install
```

**Comment by michidk** [comment]
No, I mean, what is the PHP version you run on your webserver, which you use to serve limesurvey? I am not too familiar with composer, but I would guess, that the PHP version you build the plugin with, does not matter.

**Comment by Breee** [comment]
> No, I mean, what is the PHP version you run on your webserver, which you use to serve limesurvey? I am not too familiar with composer, but I would guess that the PHP version you build the plugin with, does not matter.

Ah, I use this image: [https://hub.docker.com/r/acspri/limesurvey](https://hub.docker.com/r/acspri/limesurvey)
And the Dockerfile: [https://github.com/adamzammit/limesurvey-docker/blob/master/Dockerfile](https://github.com/adamzammit/limesurvey-docker/blob/master/Dockerfile)  uses `PHP:7.4-apache` as base. 
that is as well 7.4.14

**Comment by michidk** [comment]
Very interesting! I use [martialblog/limesurvey](https://hub.docker.com/r/martialblog/limesurvey), which is based on `php:7.4-apache` as well.

Oh, I just figured it out!
You deleted your `composer.lock` file, which contains the version of the dependencies. By deleting that file, I guess you update all dependencies to the newest version. That's why it worked in your case.

**Comment by michidk** [comment]
Okay, sorry! I misread your first post. Your fix (change version in composer.json and delete the .lock file) is basically the same as mine.

**Comment by Breee** [comment]
> Okay, sorry! I misread your first post. Your fix (change version in composer.json and delete the .lock file) is basically the same as mine.
> 
> I actually use the [martialblog/limesurvey](https://hub.docker.com/r/martialblog/limesurvey) Docker image which is based on `PHP:7.4-apache` as well.

I see, I see. 
Well, i guess we can just open a PR for @janmenzel. 
Then he can push a new release.
