### ISSUE TITLE
Displaying error messages

### ISSUE THREAD

**Issue by janmenzel** [janmenzel/AuthOpenIDConnect#8]
## Problem
After the occurrence of an error for example because of missing plugin settings there should be an error indicating what the problem is.

## Acceptance Criteria
* If the user is redirected to the authdb login after an error, an adequate message is shown.

**Comment by Shnoulle** [comment]
The simpliest way to add admin user message, without usage of the dedicated plugin part here (because 302 redirect).

`Yii::app()->setFlashMessage("Your message",'error');`

**Comment by janmenzel** [comment]
Thanks for the suggestion @Shnoulle, I filed a pull request.
Could you possibly take a look if it conforms to LimeSurvey code / behaviour 'standards'?

**Comment by Shnoulle** [comment]
There are other part where i make pull request for "LimeSurvey and Yii best usage" ;)
